-- Seed data for the MVP 8-ETF curation + rule copy, generated from app/seed/*.
-- Mirrors what `uv run python -m app.seed.load` inserts, as plain SQL so Flyway
-- can apply it directly against any environment (no separate seed step needed).

-- 102110 TIGER 200
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('102110', NULL, 'TIGER 200', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 6);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('102110', '코스피200', '실물', 1.0, FALSE, FALSE, '지수추종', '분기분배', 2.0, NULL, 0.05, '해당없음', FALSE, NULL, ARRAY['국내 주식']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('102110', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('102110', 2, '200', NULL, '한국 대표 기업 200개를 그대로 따라가는 상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('102110', '특별한 구조는 없습니다', '한국 대표 기업 200개를 그대로 담습니다. 복잡한 구조 없이 지수를 따라가는 상품입니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('102110', 'hiddenInsight', NULL, '기초지수 추종을 위하여 지수를 구성하는 종목 전체를 편입하는 완전복제전략을 원칙으로 하되, 필요시 최적화 기법을 적용하여 일부종목만 편입하는 부분복제전략을 사용.', NULL, '투자설명서 제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('102110', NULL, 'W-TR-01', '지급기준일 : 1, 4, 7, 10월 마지막영업일, 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 2);

-- 133690 TIGER 미국나스닥100
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('133690', NULL, 'TIGER 미국나스닥100', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 4);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('133690', 'NASDAQ-100', '실물', 1.0, FALSE, FALSE, '지수추종', '분기분배', 0.5, NULL, 0.0068, '미헤지', FALSE, NULL, ARRAY['미국 기술주']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('133690', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('133690', 2, '미국나스닥100', NULL, '미국 기술주 100개를 그대로 따라가는 상품');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('133690', 3, NULL, 'H', '환율에 따라 수익이 달라집니다');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('133690', '미국 주가가 올라도 손해일 수 있어요', '이름에 (H)가 없습니다. 환율 변동을 막는 장치가 없어서, 원달러 환율이 떨어지면 미국 주가 상승분이 상쇄될 수 있습니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('133690', 'hiddenInsight', NULL, '동 ETF는 환노출형으로서 별도의 환위험헤지전략을 수행하지 아니함.', NULL, '투자설명서 제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('133690', NULL, 'W-TR-01', '지급기준일 : 1, 4, 7, 10월 마지막영업일, 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('133690', NULL, 'W-FX-01', '동 ETF는 환노출형으로서 별도의 환위험헤지전략을 수행하지 아니함.', NULL, '제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('133690', NULL, 'I-FX-01', '동 ETF는 환노출형으로서 별도의 환위험헤지전략을 수행하지 아니함.', NULL, '제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 4);

-- 418660 TIGER 미국나스닥100레버리지(합성)
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('418660', NULL, 'TIGER 미국나스닥100레버리지(합성)', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 1);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('418660', 'NASDAQ-100', '합성', 2.0, TRUE, FALSE, '레버리지', '연분배', 0.8, NULL, 0.25, '미헤지', TRUE, '미래에셋증권·한국투자증권·NH투자증권·KB증권·삼성증권·신한금융투자·메리츠증권·키움증권', ARRAY['미국 기술주', '파생상품']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('418660', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('418660', 2, '미국나스닥100', NULL, '미국 기술주 100개를');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('418660', 3, '레버리지', NULL, '2배로 따라가는데');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('418660', 4, '(합성)', NULL, '실제 주식은 사지 않는 상품');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('418660', 5, NULL, 'H', '환율에 따라 수익이 달라집니다');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('418660', '오래 들고 있으면 생각과 다르게 움직여요 + 환율 영향도 있어요', '하루 단위로 2배를 맞추는 구조입니다. 여기에 이름에 (H)가 없어서, 원달러 환율이 떨어지면 미국 주가가 올라도 손해를 볼 수 있습니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', 'hiddenInsight', NULL, '미국 주식으로 구성된 ''NASDAQ-100 지수(원화환산)''를 기초지수로 하여 1좌당 순자산가치의 일간변동률을 기초지수 일간변동률의 양(陽)의 2배수로 연동하여 투자신탁재산을 운용함을 목적으로 합니다.', NULL, '투자설명서 제2부 9 (운용목표·운용방법)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', NULL, 'W-LEV-01', '1좌당 순자산가치의 일간변동률을 기초지수 일간변동률의 양(陽)의 2배수로 연동하여 투자신탁재산을 운용함을 목적으로 합니다.', NULL, '제2부 9 (운용목표)', 'KR_PROSPECTUS', FALSE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', NULL, 'W-TR-01', '지급기준일 : 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', NULL, 'W-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9 (환헤지 사항)', 'KR_PROSPECTUS', FALSE, 4);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', NULL, 'I-SYN-01', '구성종목에 TRS 계약이 편입되어 있음(예: 미국나스닥100 TRS 1~~3). 거래상대방은 상품페이지 공시 명단(미래에셋증권·한국투자증권·NH투자증권·KB증권·삼성증권·신한금융투자·메리츠증권·키움증권, 신용등급 AA~~AA+)', NULL, '제2부 9 (운용방법) / 구성종목 공시', 'KR_PROSPECTUS', FALSE, 5);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('418660', NULL, 'I-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9 (환헤지 사항)', 'KR_PROSPECTUS', FALSE, 6);

-- 435420 TIGER 미국나스닥100채권혼합50
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('435420', NULL, 'TIGER 미국나스닥100채권혼합50', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 3);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('435420', '나스닥100 + 국내채권 혼합 (5:5)', '실물', 1.0, FALSE, FALSE, '자산혼합', '분기분배', 1.5, NULL, 0.25, '미헤지', FALSE, NULL, ARRAY['주식', '채권']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('435420', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('435420', 2, '미국나스닥100', NULL, '미국 기술주 100개와');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('435420', 3, '채권', NULL, '채권을');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('435420', 4, '혼합', NULL, '함께 담는데');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('435420', 5, '50', NULL, '그 비율이 반반(50:50)인 상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('435420', '이름 끝의 ''50''이 반반이라는 뜻이에요', '이름 앞에 ''미국나스닥100''이 있어 기술주 상품으로 보이지만, 실제로는 주식과 채권을 반반씩 담습니다. 채권을 섞은 만큼 주식만 담은 상품보다 덜 오르고 덜 내립니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', 'hiddenInsight', NULL, 'NASDAQ 100(총수익) 및 KIS 국채 3-10년(총수익)의 비중을 일별 5:5로 조정하여 산출한다.', NULL, '투자설명서 제2부 9 (기초지수)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', NULL, 'W-MIX-01', '국내 채권 및 채권관련 집합투자증권을 주된 투자대상자산으로 하고 국내 주식 및 주식관련 집합투자증권에도 일부 투자. 채권에 자산총액의 90% 이하, 주식에 40% 이하를 투자합니다.', NULL, '제2부 8 (투자대상)', 'KR_PROSPECTUS', FALSE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', NULL, 'W-TR-01', '지급기준일 : 1, 4, 7, 10월 마지막영업일, 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', NULL, 'W-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9 (환헤지 사항)', 'KR_PROSPECTUS', FALSE, 4);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', NULL, 'I-MIX-01', '국내 채권 및 채권관련 집합투자증권을 주된 투자대상자산으로 하고 국내 주식 및 주식관련 집합투자증권에도 일부 투자. 채권에 자산총액의 90% 이하, 주식에 40% 이하를 투자합니다.', NULL, '제2부 8', 'KR_PROSPECTUS', FALSE, 5);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('435420', NULL, 'I-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9', 'KR_PROSPECTUS', FALSE, 6);

-- 441680 TIGER 미국나스닥100커버드콜(합성)
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('441680', NULL, 'TIGER 미국나스닥100커버드콜(합성)', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 2);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('441680', 'Cboe Nasdaq-100 BuyWrite V2 (TR)', '합성', 1.0, FALSE, FALSE, '커버드콜', '월분배', 12.3, NULL, 0.37, '미헤지', TRUE, '미래에셋증권·한국투자증권·NH투자증권·KB증권·삼성증권·신한금융투자·메리츠증권·키움증권', ARRAY['NASDAQ-100 포트폴리오', '콜옵션']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('441680', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('441680', 2, '미국나스닥100', NULL, '미국 기술주 100개를 담고');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('441680', 3, '커버드콜', NULL, '매달 돈을 받는 대신 큰 상승은 포기하며');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('441680', 4, '(합성)', NULL, '실제 주식은 사지 않는 상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('441680', '나스닥이 크게 올라도 그만큼 못 받아요', '매달 받는 돈은 콜옵션을 팔아서 만듭니다. 그래서 나스닥이 크게 오르는 구간에서는 그 상승분을 온전히 받지 못합니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('441680', 'hiddenInsight', NULL, 'CBOE Nasdaq-100 BuyWrite V2 지수(Total Return)(원화환산)는 Nasdaq-100 포트폴리오를 보유하면서 ATM Nasdaq-100 콜옵션을 매도한 수익률이 합산되어 산출되는 Nasdaq-100 커버드콜 전략 지수입니다.', NULL, '투자설명서 제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('441680', NULL, 'W-CC-01', 'Nasdaq-100 포트폴리오를 보유하면서 ATM Nasdaq-100 콜옵션을 매도한 수익률이 합산되어 산출되는 커버드콜 전략 지수입니다.', NULL, '제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('441680', NULL, 'I-SYN-01', '구성종목에 TRS 계약이 편입되어 있음(예: 미국나스닥100 TRS 1~~3). 거래상대방은 상품페이지 공시 명단(미래에셋증권·한국투자증권·NH투자증권·KB증권·삼성증권·신한금융투자·메리츠증권·키움증권, 신용등급 AA~~AA+)', NULL, '제2부 9 (운용방법) / 구성종목 공시', 'KR_PROSPECTUS', FALSE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('441680', NULL, 'I-DIV-01', '지급기준일 : 매월 마지막영업일, 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 4);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('441680', NULL, 'I-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9', 'KR_PROSPECTUS', FALSE, 5);

-- 448290 TIGER 미국S&P500(H)
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('448290', NULL, 'TIGER 미국S&P500(H)', 'KR', '미래에셋자산운용', NULL, NULL, 'manual', 5);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('448290', 'S&P 500', '실물', 1.0, FALSE, FALSE, '지수추종', '분기분배', 1.0, NULL, 0.07, '헤지', FALSE, NULL, ARRAY['미국 주식']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('448290', 1, 'TIGER', NULL, '미래에셋이 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('448290', 2, '미국S&P500', NULL, '미국 큰 회사 500개를 그대로 따라가고');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('448290', 3, '(H)', NULL, '환율 걱정은 없는 상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('448290', '환율 걱정은 없지만 비용이 듭니다', '(H)는 환율 변동을 막는 장치입니다. 대신 그 장치를 유지하는 비용이 수익률에서 빠집니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('448290', 'hiddenInsight', NULL, '이 투자신탁은 S&P Dow Jones Indices에서 발표하는 ''S&P 500''를 기초지수로 하는 상장지수투자신탁으로서, 미국에 상장된 주식에 투자신탁 자산총액의 60% 이상 투자합니다. 한편, 동 ETF는 환헤지형으로서 별도의 환위험헤지전략을 수행합니다.', NULL, '투자설명서 제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('448290', NULL, 'W-TR-01', '지급기준일 : 1, 4, 7, 10월 마지막영업일, 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'KR_PROSPECTUS', FALSE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('448290', NULL, 'I-FXH-01', '동 ETF는 환헤지형으로서 별도의 환위험헤지전략을 수행합니다.', NULL, '제2부 9 (운용방법)', 'KR_PROSPECTUS', FALSE, 3);

-- QYLD Global X NASDAQ 100 Covered Call ETF
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('QYLD', NULL, 'Global X NASDAQ 100 Covered Call ETF', 'US', 'Global X', NULL, 'NASDAQ', 'manual', 8);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('QYLD', 'Cboe NASDAQ-100 BuyWrite V2', '실물', 1.0, FALSE, FALSE, '커버드콜', '월분배', 11.5, NULL, 0.6, '미헤지', FALSE, NULL, ARRAY['NASDAQ 100', 'Covered Call']::text[], FALSE, 'manual', NULL, '2026-08-31 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('QYLD', 1, 'Global X', NULL, '글로벌엑스가 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('QYLD', 2, 'NASDAQ 100', NULL, '미국 기술주 100개를 담고');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('QYLD', 3, 'Covered Call', NULL, '매달 돈을 받는 대신 큰 상승은 포기하는');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('QYLD', 4, 'ETF', NULL, '상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('QYLD', '나스닥이 크게 올라도 그만큼 못 받아요', '커버드콜은 앞으로 오를 수 있는 몫을 미리 팔아 매달 분배금을 만듭니다. 그래서 크게 오르는 구간에서 그 상승분을 온전히 받지 못합니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('QYLD', 'hiddenInsight', NULL, '커버드콜 옵션을 매도함으로써 이 펀드는 옵션 행사가격을 초과하는 참조지수 가치 상승분의 이익을 포기하게 되며, 하락에 대한 위험은 계속 부담할 수 있습니다.', 'By writing covered call options on a portion of the Fund''s portfolio in return for the receipt of premiums, the Fund will give up the opportunity to benefit from potential increases in the value of the Reference Index above the exercise prices of such options, but may continue to bear the risk of declines in the value of the Reference Index.', '요약투자설명서 — 주요 투자전략 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('QYLD', NULL, 'W-CC-01', '커버드콜 옵션을 매도함으로써 이 펀드는 옵션 행사가격을 초과하는 참조지수 가치 상승분의 이익을 포기하게 됩니다.', NULL, '요약투자설명서 — 주요 투자전략 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('QYLD', NULL, 'I-DIV-01', '2014년 1월부터 2026년 8월까지 매월 빠짐없이 분배금을 지급한 지급기준일(ex-date)·기준일(record date)·지급일(payable date)·금액 내역이 공시되어 있습니다 (예: 2026-08-24 지급기준일, 주당 $0.1829).', NULL, '운용사 법정 공시 영역 — Distribution History (globalxetfs.com/funds/qyld)', 'ISSUER_DISCLOSURE', TRUE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('QYLD', NULL, 'I-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9', 'US_SUMMARY_PROSPECTUS', TRUE, 4);

-- TQQQ ProShares UltraPro QQQ
INSERT INTO etf_master (code, isin, name, market, manager, listed_at, exchange, source, display_order) VALUES ('TQQQ', NULL, 'ProShares UltraPro QQQ', 'US', 'ProShares', NULL, 'NASDAQ', 'manual', 7);
INSERT INTO etf_profile (code, base_index, replication, leverage, daily_rebalancing, is_active, strategy, distribution, distribution_yield, target_year, total_expense, fx_hedge, counterparty_risk, counterparty, main_assets, is_complex_product, extracted_by, extraction_run_id, reviewed_at) VALUES ('TQQQ', 'Nasdaq-100', '합성', 3.0, TRUE, FALSE, '레버리지', '분기분배', 0.5, NULL, 0.82, '미헤지', TRUE, NULL, ARRAY['스왑 계약', '선물 계약']::text[], FALSE, 'ai', NULL, '2026-09-02 00:00:00+09:00');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('TQQQ', 1, 'ProShares', NULL, '프로셰어스가 만든');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('TQQQ', 2, 'UltraPro', NULL, '3배로');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('TQQQ', 3, 'QQQ', NULL, '미국 기술주 100개(나스닥100)를');
INSERT INTO etf_name_token (code, seq, text, absent, translation) VALUES ('TQQQ', 4, NULL, '방향 표기 없음', '같은 방향으로 따라가는 상품');
INSERT INTO etf_hidden_insight (code, summary, body) VALUES ('TQQQ', '이름에 ''3배''라는 말이 없어요', '''UltraPro''가 3배를 뜻합니다. 그리고 이 3배는 하루 단위로만 맞춰집니다. 설명서에는 "지수가 장중 33% 하락에 근접하면 투자금 전액을 잃을 수 있다"고 적혀 있습니다.');
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', 'hiddenInsight', NULL, '이 펀드는 하루를 제외한 어떤 기간에 대해서도 지수의 일간 성과의 3배(3x)를 달성하는 것을 목표로 하지 않습니다.', 'The Fund does not seek to achieve three times (3x) the daily performance of the Index (the "Daily Target") for any period other than a day.', '요약투자설명서 — 주요 정보 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 1);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'W-LEV-01', '이 펀드는 하루를 제외한 어떤 기간에 대해서도 지수의 일간 성과의 3배를 달성하는 것을 목표로 하지 않습니다.', 'The Fund does not seek to achieve three times (3x) the daily performance of the Index (the "Daily Target") for any period other than a day.', '요약투자설명서 — 주요 정보 / 주요 위험 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 2);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'W-LEV-01', '지수가 장중 33% 손실에 근접하면 투자금 전액을 잃을 수 있습니다.', 'If the Index approaches a 33% loss at any point in the day, you could lose your entire investment.', '요약투자설명서 — 주요 정보 / 주요 위험 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 3);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'W-TR-01', '지급기준일 : 회계기간종료일(비영업일인 경우 직전영업일)', NULL, '제2부 14-가 (이익 배분)', 'US_SUMMARY_PROSPECTUS', TRUE, 4);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'W-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9 (환헤지 사항)', 'US_SUMMARY_PROSPECTUS', TRUE, 5);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'I-SYN-01', '이 펀드는 스왑 계약과 선물 계약을 통해 지수 노출을 확보합니다.', NULL, '요약투자설명서 — 주요 투자전략 (Summary Prospectus, SEC 공시)', 'US_SUMMARY_PROSPECTUS', TRUE, 6);
INSERT INTO evidence (code, field, rule_code, quote, quote_original, location, source_type, translated, display_order) VALUES ('TQQQ', NULL, 'I-FX-01', '환헤지를 하지 아니함', NULL, '제2부 9', 'US_SUMMARY_PROSPECTUS', TRUE, 7);

-- rule_config + rule_config_variant
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('W-LEV-01', 'warning', 1, '원금 손실', '오래 들고 있으면 손해 볼 수 있어요', '{기간} 보유하실 계획과 맞지 않습니다', '이 상품은 하루 단위로 지수의 {배율}배를 맞추도록 만들어졌습니다. 지수가 올랐다 내렸다를 반복하면, {기간} 뒤에는 지수가 제자리여도 원금이 줄어 있을 수 있습니다.', '꼭 필요한 돈이라고 하셨는데, 이 상품은 원금이 예상보다 크게 줄어들 수 있는 구조입니다.', 'A');
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('W-MIX-01', 'warning', 2, '목적 불일치', '나스닥이 올라도 그만큼 따라가지 못해요', '차익을 노리는 목적과 맞지 않을 수 있습니다', '이름 앞에 ''미국나스닥100''이 있어 기술주 상품으로 보이지만, 이름 끝의 ''50''은 주식과 채권을 반반씩 담는다는 뜻입니다. 채권을 섞은 만큼 나스닥이 크게 올라도 그만큼 따라가지 못합니다.', '목표한 금액을 모으려는 계획이라면, 기대하신 속도보다 천천히 불어날 수 있다는 점을 감안하셔야 합니다.', 'C');
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('W-CC-01', 'warning', 2, '목적 불일치', '가격이 올라도 그만큼 못 받아요', '차익을 노리는 목적과 맞지 않습니다', '이 상품이 매달 주는 돈은, 앞으로 오를 수 있는 몫을 미리 팔아서 만듭니다. 그래서 크게 오르는 구간에서 그 상승분을 온전히 받지 못합니다.', '목표한 금액이 있으시다면, 시장이 크게 올라도 그만큼 따라가지 못한다는 점을 미리 아셔야 합니다.', 'B');
INSERT INTO rule_config_variant (rule_code, purpose, summary, title, body) VALUES ('W-CC-01', 'CAPITAL_GAIN', '가격이 올라도 그만큼 못 받아요', '차익을 노리는 목적과 맞지 않습니다', '이 상품이 매달 주는 돈은, 앞으로 오를 수 있는 몫을 미리 팔아서 만듭니다. 그래서 크게 오르는 구간에서 그 상승분을 온전히 받지 못합니다.');
INSERT INTO rule_config_variant (rule_code, purpose, summary, title, body) VALUES ('W-CC-01', 'GROWTH', '오래 둘수록 지수와 차이가 벌어져요', '오래 묻어두는 목적과 맞지 않습니다', '이 상품이 매달 주는 돈은, 앞으로 오를 수 있는 몫을 미리 팔아서 만듭니다. 이 차이는 오래 둘수록 쌓입니다. 같은 구조의 상품(QYLD)은 지난 10년간 8.79% 올랐고, 같은 기간 나스닥100 지수는 19.70% 올랐습니다.');
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('W-TR-01', 'warning', 3, '현금 흐름', '매달 받는 돈이 없어요', '정기적으로 현금을 받고 싶다는 목적과 맞지 않습니다', '이 상품은 1년에 한 번, 그것도 적은 금액만 나눠줍니다. 매달 현금이 필요하시다면 직접 팔아야 합니다.', '정해진 시점에 돈이 필요하시다면, 그때 시장 상황이 나빠도 팔아야 할 수 있습니다.', 'E');
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('W-FX-01', 'warning', 3, '현금 흐름', '환율에 따라 받는 돈이 달라져요', '안정적인 현금 목적과 맞지 않을 수 있습니다', '환율 변동을 막는 장치가 없습니다. 받는 돈이 환율에 따라 달라집니다.', '매달 일정한 금액이 필요하신 상황이라면, 환율에 따라 들쑥날쑥해질 수 있다는 점을 감안하셔야 합니다.', 'D');
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-SYN-01', 'info', NULL, NULL, '주식을 직접 사지 않고 증권사와 약속만 했어요', NULL, '이 상품은 {기초자산}을 직접 사는 대신, 증권사와 계약(TRS)을 맺어 수익률을 받는 구조입니다. 해외 지수를 따라갈 때는 이 방식이 오히려 오차가 작은 경우가 많습니다. 다만 계약 상대방(**{거래상대방}**)이 약속을 지키지 못할 경우 영향을 받을 수 있다는 점은 실제로 주식을 갖고 있는 것과 다른 부분입니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-FX-01', 'info', NULL, NULL, '환율에 따라 수익이 달라져요', NULL, '환율 변동을 막는 장치가 없습니다. 미국 주가가 올라도 원달러 환율이 떨어지면 수익이 줄어들 수 있고, 반대로 환율이 오르면 수익이 늘어날 수도 있습니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-FXH-01', 'info', NULL, NULL, '환율이 오르내려도 크게 상관없어요', NULL, '원달러 환율이 변해도 수익률에 미치는 영향이 작습니다. 대신 그 장치를 유지하는 비용이 듭니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-DIV-01', 'info', NULL, NULL, '매달 돈을 나눠줘요', NULL, '매월 마지막 영업일 기준으로 분배금을 지급합니다. 다만 그 돈이 어디서 나오는지(수익인지, 원금인지) 함께 살펴보시는 것이 좋습니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-MIX-01', 'info', NULL, NULL, '주식과 채권을 함께 담고 있어요', NULL, '하나의 상품 안에 주식과 채권이 함께 들어 있습니다. 주식만 담은 상품보다 덜 흔들리지만, 크게 오를 때도 덜 오릅니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('I-OVS-01', 'info', NULL, NULL, '이 상품은 미국에 상장되어 있어요', NULL, '한국에서 이 상품을 살 때는, 투자설명서를 확인하는 절차가 법적으로 요구되지 않습니다. 국내 상장 상품과 달리 한국어 설명서도 없습니다. 저희가 미국 공시 문서(SEC)를 대신 읽어 정리했습니다.', NULL, NULL);
INSERT INTO rule_config (code, level, priority, category, summary, title, body, purpose_addon, widget_type) VALUES ('OK-01', 'ok', NULL, NULL, '선택하신 조건 기준으로 어긋나는 부분은 발견되지 않았습니다', NULL, '다만 모든 투자에는 원금 손실 가능성이 있습니다.', NULL, NULL);
